theme: jekyll-theme-cayman
title: "Happy Birthday Sandy!!"
description: "Welcome to Sandy's 57th Birthday Website"
show_downloads: false
github:
  is_project_page: false
defaults:
  - scope:
      path: "images"
    values:
      image: true
